### ISSUE TITLE
icalendar out of date when setting up developer environment

### ISSUE THREAD

**Issue by NABarnes** [sourcesimian/mqtt-ical#2]
Hi,

When setting up the developer environment as per the README instructions on Debian 12, the following error is raised and the setup fails:

error: icalendar 4.0.3 is installed but icalendar<7.0.0,>=5.0.0 is required by {'recurring-ical-events'}

**Comment by sourcesimian** [comment]
Thank you for your feedback. This project is no longer under active development. I've moved to using Node-RED and https://github.com/naimo84/node-red-contrib-ical-events

Should you wish to propose a pull request I will review.

**Comment by NABarnes** [comment]
Hi,
Thanks for the speedy reply. I'm using node-red-contrib-ical-events at the moment and need to find something to move to due to its complete inability to deal with repeating events in any reliable way :-(
I did a quick Google and mqtt-ical seemed to be the answer.
Ah well, thank you anyway. I may just have to persevere with the current solution.

**Comment by sourcesimian** [comment]
That is weird, node-red-contrib-ical-events with recurrence works well for me.

Keep in mind that mqtt-ical is mostly just glue that uses these Python modules: icalendar and recurring-ical-events
